// Package def2lib20 builds x86 COFF import libraries (.lib) from module
// definition files (.def) in the classic "long" format: every imported
// function is a real COFF object member, exactly like the libraries written
// by Microsoft LINK 2.x–5.x (and by VC6 with /LINK50COMPAT) — the only
// format the Alaska Xbase++ linker (ALINK) understands.
//
// Files: def.go is the producer (.def → Def, read with linereader), coff.go
// the consumer (Def → COFF objects → archive bytes) and def2lib20.go the API
// that resolves names and options between the two.
//
// Library layout (see the PE/COFF specification §7 and §8):
//
//	!<arch>\n
//	/                first linker member  (big-endian directory, member order)
//	/                second linker member (little-endian directory, sorted names)
//	//               longnames member, only when a member name exceeds 16 bytes
//	<dll>/           __IMPORT_DESCRIPTOR_<base>: .idata$2 entry + DLL name (.idata$6)
//	<dll>/           __NULL_IMPORT_DESCRIPTOR:   .idata$3 terminator
//	<dll>/           \x7f<base>_NULL_THUNK_DATA:  .idata$5 + .idata$4 terminators
//	<dll>/           one member per export: .text thunk "jmp [__imp_x]" (COMDAT),
//	                 .idata$5 IAT slot (COMDAT __imp_x), .idata$4 ILT slot and
//	                 .idata$6 hint/name (associative COMDAT)
//
// All import members share the archive member name "<dll>/": the relocations
// of the descriptor against the undefined section symbols .idata$4/.idata$5
// resolve to the start of the tables assembled from every member with that
// name (PE/COFF spec §5.2).
//
// The generated bytes follow the 1995 libraries shipped with Xbase++
// (KERNEL32.LIB, "Microsoft LINK 2.60") field by field: section flags,
// COMDAT selections, symbol classes and values, the PE32 optional header in
// the descriptor member. NONAME and DATA exports are not supported yet.
//
// Typical use:
//
//	n, err := def2lib20.BuildFile("ot4xb.def", "ot4xb.lib", def2lib20.Options{})
//
// or, for C cdecl exports, Options{Prefix: "_"}.
package def2lib20
